# Generated by Django 4.2.13 on 2024-06-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("music_apis", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="playlisttrack",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlist_tracks",
                to="music_apis.playlist",
            ),
        )
    ]
